<a href="https://colab.research.google.com/github/adityajain2407/DAV-1-Feb23-Tue/blob/main/04_Numpy_doubts_solving.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3] , [4,5] , [6,7,8,9]])

<ipython-input-2-3e4baf3b092b>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[1,2,3] , [4,5] , [6,7,8,9]])


In [3]:
print(a)

[list([1, 2, 3]) list([4, 5]) list([6, 7, 8, 9])]


In [4]:
b = np.array([[1,2,3] , [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
x = np.array([[200,200,200],
              [300,300,300],
              [400,400,400]]
             )

v = np.array([200,300,400])

print((x / v[:,None])[1][1])

1.0


In [6]:
v = np.array([200,300,400])

In [7]:
v[:,None]

array([[200],
       [300],
       [400]])

In [10]:
a = np.array([4,6,8,7,1])

In [11]:
np.argsort(a)

array([4, 0, 1, 3, 2])

In [13]:
birds = np.array(["a", "b", "c", "d"])
age =   np.array([2, 7, 1, 5])

In [14]:
age_index_sorted = np.argsort(age)

In [15]:
print(age_index_sorted)

[2 0 3 1]


In [16]:
print(birds[age_index_sorted])

['c' 'a' 'd' 'b']


In [19]:
print(birds[age_index_sorted][::-1]) #printing in descending order

['b' 'd' 'a' 'c']


In [ ]:
#prem's logic

sorted_age_index = np.argsort(age)
result = np.sort(birds)[sorted_age_index]
print(result)

In [20]:
#multi-indexing


a = np.array([1,5,7,2])

In [21]:
print(a[[2,0,1]])

[7 1 5]


In [22]:
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))


['Astha' 'Raghavendra' 'Ram']


In [23]:
print(np.sort(np.array(['Ram','ram','Raghavendra'])))

['Raghavendra' 'Ram' 'ram']


In [24]:
print(np.sort(np.array(['ram','Ram','Raghavendra'])))

['Raghavendra' 'Ram' 'ram']


In [25]:
ord("A")

65

In [26]:
ord("a")

97

In [27]:
"a" > "A"

True

In [28]:
"a" < "Z"

False

In [29]:
ord("a")

97

In [30]:
ord("Z")

90

In [31]:
5545//10

554

In [33]:
int(str(5545)[0])

5