<a href="https://colab.research.google.com/github/adityajain2407/DAV-1-Feb23-Tue/blob/main/05_misc_concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.arange(4)

In [ ]:
print(a)

[0 1 2 3]


In [ ]:
b = a.reshape(2,2)

In [ ]:
np.shares_memory(a,b)

True

In [ ]:
a[0] = 100

In [ ]:
print(b)

[[100   1]
 [  2   3]]


In [ ]:
c = a.copy()

In [ ]:
print(a)

[100   1   2   3]


In [ ]:
print(c)

[100   1   2   3]


In [ ]:
a[1] = 101

In [ ]:
print(a)

[100 101   2   3]


In [ ]:
print(c)

[100   1   2   3]


In [ ]:
np.shares_memory(a,c)

False

In [ ]:
a = np.arange(5)

In [ ]:
print(a)

[0 1 2 3 4]


In [ ]:
b = a + 2

In [ ]:
print(b)

[2 3 4 5 6]


In [ ]:
np.shares_memory(a,b)

False

In [ ]:
a[0] = 10

In [ ]:
print(a)

[10  1  2  3  4]


In [ ]:
print(b)

[2 3 4 5 6]


In [ ]:
#shallow copy - same address
#deep copy - different address

In [ ]:
a = np.arange(10)

In [ ]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
b = a[::2]

In [ ]:
print(b)

[0 2 4 6 8]


In [ ]:
np.shares_memory(a,b)

True

In [ ]:
a[0] = 20

In [ ]:
print(b)

[20  2  4  6  8]


In [ ]:
a[1] = 30

In [ ]:
print(a)

[20 30  2  3  4  5  6  7  8  9]


In [ ]:
print(b)

[20  2  4  6  8]


In [ ]:
a = np.arange(5)

In [ ]:
b = a.view()

In [ ]:
np.shares_memory(a,b)

True

In [ ]:
#special cases

In [ ]:
a = np.array([1,4,2.5,7])

In [ ]:
a

array([1. , 4. , 2.5, 7. ])

In [ ]:
print(a)

[1.  4.  2.5 7. ]


In [ ]:
a = np.array([1, 'a'])

In [ ]:
a

array(['1', 'a'], dtype='<U21')

In [ ]:
a = np.array([1, 'm' , [1,2,3]])

<ipython-input-45-d973f767710d>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([1, 'm' , [1,2,3]])


In [ ]:
a

array([1, 'm', list([1, 2, 3])], dtype=object)

In [ ]:
a = np.array([1,'m' , [1,2,3]] , dtype = 'object')

In [ ]:
b = a.copy()

In [ ]:
np.shares_memory(a,b) #hw

False

In [ ]:
a[2][0] = 5

In [ ]:
print(b)

[1 'm' list([5, 2, 3])]


In [ ]:
a[2][1] = 100

In [ ]:
print(b)

[1 'm' list([5, 100, 3])]


In [ ]:
import copy

In [ ]:
a = np.array([1, 'm' , [1,2,3]], dtype = 'object')

In [ ]:
b = copy.deepcopy(a)

In [ ]:
a[2][0] = 10

In [ ]:
print(a)

[1 'm' list([10, 2, 3])]


In [ ]:
print(b)

[1 'm' list([1, 2, 3])]


In [ ]:
#Misc

In [ ]:
#splitting

In [ ]:
x = np.arange(9)

In [ ]:
print(x)

[0 1 2 3 4 5 6 7 8]


In [ ]:
b = np.split(x , 3)

In [ ]:
print(b)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [ ]:
type(b)

list

In [ ]:
b = np.array(np.split(x , 3))

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.ndim

2

In [ ]:
np.split(x,2)

ValueError: ignored

In [ ]:
print(x)

[0 1 2 3 4 5 6 7 8]


In [ ]:
np.split(x, [3,5,6])

[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8])]

In [ ]:
x = np.arange(5,15)

In [ ]:
print(x)

[ 5  6  7  8  9 10 11 12 13 14]


In [ ]:
np.split(x , [2,4,7])

[array([5, 6]), array([7, 8]), array([ 9, 10, 11]), array([12, 13, 14])]

In [ ]:
x = np.arange(16).reshape(4,4)

In [ ]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
np.hsplit(x,2) #split across horizontal axis

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.hsplit(x, [1,2])

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
np.vsplit(x, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
np.vsplit(x, [3])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [ ]:
data = np.arange(5)

In [ ]:
print(data)

[0 1 2 3 4]


In [ ]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
d1 = np.arange(5)

d2 = np.arange(6,11)

In [ ]:
np.vstack((d1, d2))

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [ ]:
d1 = np.arange(5).reshape(5,1)

In [ ]:
print(d1)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [ ]:
d2 = np.arange(6,11).reshape(5,1)

In [ ]:
print(d2)

[[ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [ ]:
np.hstack((d1, d2))

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10]])

In [ ]:
np.hstack((d1, d2, d1, d2))

array([[ 0,  6,  0,  6],
       [ 1,  7,  1,  7],
       [ 2,  8,  2,  8],
       [ 3,  9,  3,  9],
       [ 4, 10,  4, 10]])

In [ ]:
z = np.array([[2,4]])

In [ ]:
z.ndim

2

In [ ]:
z.shape

(1, 2)

In [ ]:
z1 = np.concatenate([z,z] , axis = 0)
print(z1)

[[2 4]
 [2 4]]


In [ ]:
z1 = np.concatenate([z,z] , axis = 1)
print(z1)

[[2 4 2 4]]


In [ ]:
z1.shape

(1, 4)

In [ ]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
a.shape

(6,)

In [ ]:
arr = a.reshape(1,-1)
print(arr)

[[0 1 2 3 4 5]]


In [ ]:
arr.shape

(1, 6)

In [ ]:
a = np.arange(6)

In [ ]:
print(a)

[0 1 2 3 4 5]


In [ ]:
a.shape

(6,)

In [ ]:
a1 = np.expand_dims(a, axis = 0)
print(a1)

[[0 1 2 3 4 5]]


In [ ]:
a1.shape

(1, 6)

In [ ]:
a = np.arange(5)

In [ ]:
print(a)

[0 1 2 3 4]


In [ ]:
a.shape

(5,)

In [ ]:
a2 = np.expand_dims(a, axis = 1)

In [ ]:
a2.shape

(5, 1)

In [ ]:
print(a2)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [ ]:
a3 = a.reshape(-1, 1)
print(a3)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [ ]:
a = np.arange(6)

In [ ]:
print(a)

[0 1 2 3 4 5]


In [ ]:
a[np.newaxis, :] #expand_dims(a, axis = 0)

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
#expand_dims(a, axis = 1)

In [ ]:
a[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
#squeeze

In [ ]:
a = np.arange(9).reshape(1,1,9)

In [ ]:
print(a)

[[[0 1 2 3 4 5 6 7 8]]]


In [ ]:
a.shape

(1, 1, 9)

In [ ]:
a.ndim

3

In [ ]:
a2 = np.squeeze(a)

In [ ]:
print(a2)

[0 1 2 3 4 5 6 7 8]


In [ ]:
a2.shape

(9,)

In [ ]:
print(a)

[[[0 1 2 3 4 5 6 7 8]]]


In [ ]:
a.shape

(1, 1, 9)

In [ ]:
a3 = np.squeeze(a, axis = 1)

In [ ]:
a3.shape

(1, 9)

In [ ]:
a4 = np.squeeze(a3, axis = 0)
print(a4)

[0 1 2 3 4 5 6 7 8]


In [ ]:
a4.shape

(9,)