<a href="https://colab.research.google.com/github/adityajain2407/DAV-1-Feb23-Tue/blob/main/05_misc_concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a = np.arange(4)

In [4]:
print(a)

[0 1 2 3]


In [5]:
b = a.reshape(2,2)

In [6]:
np.shares_memory(a,b)

True

In [7]:
a[0] = 100

In [8]:
print(b)

[[100   1]
 [  2   3]]


In [9]:
c = a.copy()

In [10]:
print(a)

[100   1   2   3]


In [11]:
print(c)

[100   1   2   3]


In [12]:
a[1] = 101

In [13]:
print(a)

[100 101   2   3]


In [14]:
print(c)

[100   1   2   3]


In [15]:
np.shares_memory(a,c)

False

In [17]:
a = np.arange(5)

In [18]:
print(a)

[0 1 2 3 4]


In [19]:
b = a + 2

In [20]:
print(b)

[2 3 4 5 6]


In [21]:
np.shares_memory(a,b)

False

In [22]:
a[0] = 10

In [23]:
print(a)

[10  1  2  3  4]


In [24]:
print(b)

[2 3 4 5 6]


In [25]:
#shallow copy - same address
#deep copy - different address

In [26]:
a = np.arange(10)

In [27]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
b = a[::2]

In [29]:
print(b)

[0 2 4 6 8]


In [30]:
np.shares_memory(a,b)

True

In [31]:
a[0] = 20

In [32]:
print(b)

[20  2  4  6  8]


In [33]:
a[1] = 30

In [34]:
print(a)

[20 30  2  3  4  5  6  7  8  9]


In [35]:
print(b)

[20  2  4  6  8]


In [36]:
a = np.arange(5)

In [37]:
b = a.view()

In [38]:
np.shares_memory(a,b)

True

In [39]:
#special cases

In [47]:
a = np.array([1,4,2.5,7])

In [48]:
a

array([1. , 4. , 2.5, 7. ])

In [41]:
print(a)

[1.  4.  2.5 7. ]


In [42]:
a = np.array([1, 'a'])

In [43]:
a

array(['1', 'a'], dtype='<U21')

In [45]:
a = np.array([1, 'm' , [1,2,3]])

<ipython-input-45-d973f767710d>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([1, 'm' , [1,2,3]])


In [46]:
a

array([1, 'm', list([1, 2, 3])], dtype=object)

In [52]:
a = np.array([1,'m' , [1,2,3]] , dtype = 'object')

In [53]:
b = a.copy()

In [54]:
np.shares_memory(a,b) #hw

False

In [55]:
a[2][0] = 5

In [56]:
print(b)

[1 'm' list([5, 2, 3])]


In [57]:
a[2][1] = 100

In [58]:
print(b)

[1 'm' list([5, 100, 3])]


In [59]:
import copy

In [60]:
a = np.array([1, 'm' , [1,2,3]], dtype = 'object')

In [61]:
b = copy.deepcopy(a)

In [62]:
a[2][0] = 10

In [63]:
print(a)

[1 'm' list([10, 2, 3])]


In [64]:
print(b)

[1 'm' list([1, 2, 3])]


In [65]:
#Misc